version: 2.1
jobs:
  build:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "install dependencies" 
          command: |
            sudo apt update
            sudo apt install openssh-server python3.9 -y
            python3.9 -m pip install --upgrade pip
            python3.9 -m pip install -r requirements.txt
            ansible-galaxy collection install linode.cloud community.crypto community.mysql

      - run:
          name: "copy run script to path"
          command: |
            mkdir $HOME/.local/bin
            sudo cp scripts/run.sh $HOME/.local/bin/run
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV

      - run:
          name: "build"
          command: |
            export TOKEN=$TOKEN
            export VARS_URL=$VARS_URL
            run build

  test: 
    machine:
      image: ubuntu-2004:202010-01

    steps:
      - run:
          name: "test ubuntu 20.04"
          command: run test:ubuntu2004

      - run:
          name: "test debian 10"
          command: run test:ubuntu2004
      
workflows:
  build_and_test:
    jobs:
      - build:
          context:
            - LINODE_API_TOKEN
            - TEST_VARS_URL
      - test:
          requires:
            - build
