version: 2.1
jobs:
  ubuntu2004:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "install dependencies" 
          command: |
            sudo apt update
            sudo apt install python3-distutils python3-apt python3.9 -y
            python3.9 -m pip install --upgrade pip
            python3.9 -m pip install -r requirements.txt
            ansible-galaxy collection install linode.cloud community.crypto community.mysql

      - run:
          name: "copy run script to path"
          command: |
            mkdir $HOME/.local/bin
            sudo cp scripts/run.sh $HOME/.local/bin/run
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV

      - run:
          name: "build"
          command: |
            export TOKEN=$TOKEN
            export VARS_URL=$VARS_URL
            run build
      - run:
          name: "test ubuntu 20.04"
          command: run test:ubuntu2004

  debian10:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - run:
          name: "install dependencies" 
          command: |
            sudo apt update
            sudo apt install python3-distutils python3-apt python3.9 -y
            python3.9 -m pip install --upgrade pip
            python3.9 -m pip install -r requirements.txt
            ansible-galaxy collection install linode.cloud community.crypto community.mysql

      - run:
          name: "copy run script to path"
          command: |
            mkdir $HOME/.local/bin
            sudo cp scripts/run.sh $HOME/.local/bin/run
            echo "export PATH=$HOME/.local/bin:$PATH" >> $BASH_ENV

      - run:
          name: "build"
          command: |
            export TOKEN=$TOKEN
            export VARS_URL=$VARS_URL
            run build
      - run:
          name: "test ubuntu 20.04"
          command: run test:debian10
      
workflows:
  build_and_test:
    jobs:
      - ubuntu2004:
          context:
            - LINODE_API_TOKEN
            - TEST_VARS_URL
      - debian10:
          context:
            - LINODE_API_TOKEN
            - TEST_VARS_URL
