---
name: Molecule
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: macos-11
    #runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.9]

    steps:
      - name: install docker
        run: |
          brew cask install docker
          # allow the app to run without confirmation
          xattr -d -r com.apple.quarantine /Applications/Docker.app
  
          # preemptively do docker.app's setup to avoid any gui prompts
          sudo /bin/cp /Applications/Docker.app/Contents/Library/LaunchServices/com.docker.vmnetd /Library/PrivilegedHelperTools
          sudo /bin/cp /Applications/Docker.app/Contents/Resources/com.docker.vmnetd.plist /Library/LaunchDaemons/
          sudo /bin/chmod 544 /Library/PrivilegedHelperTools/com.docker.vmnetd
          sudo /bin/chmod 644 /Library/LaunchDaemons/com.docker.vmnetd.plist
          sudo /bin/launchctl load /Library/LaunchDaemons/com.docker.vmnetd.plist
          open -g -a Docker.app
  
          # Wait for the server to start up, if applicable.
          i=0
          while ! docker system info &>/dev/null; do
            (( i++ == 0 )) && printf %s '-- Waiting for Docker to finish starting up...' || printf '.'
            sleep 1
          done
          (( i )) && printf '\n'
  
          echo "-- Docker is ready."
      - uses: actions/checkout@v2
        with:
          path: molecule_test
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Test ansible vars
        run: |
          test_vars=$(cat molecule_test/group_vars/galera/vars)
          galera_ansible_vars=$(curl -s https://gist.githubusercontent.com/linodeproservices/85d4b26ea990b69360c0f03c3e39c851/raw/2f768d2de0042b09f5a9502dedc6f321abb287b9/galera_ansible_vars)
          diff -w <(echo "$test_vars") <(echo "$galera_ansible_vars")
      - name: Install dependencies
        run: |
          brew install docker docker-machine
          cd molecule_test
          python3 -m pip install --upgrade pip
          python3 -m pip install wheel==0.37.0
          python3 -m pip install -r requirements.txt
      - name: 'Test Ubuntu 20.04'
        run: |
          cd molecule_test/tests
          molecule test -s ubuntu20.04
      - name: 'Test Debian 10'
        run: |
          cd molecule_test/tests
          molecule test -s debian10
