---
name: Ubuntu 20.04
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 2
      matrix:
        python-version: [3.8, 3.9]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: set up python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: integrity checks
        run: |
          echo "53f93fb473e306bdb40b503229c40464cf60e0e2188d58875a8532e50c7c77b0 group_vars/galera/vars" | sha256sum -c

      - name: install dependencies
        run: |
          sudo apt update
          sudo apt install openssh-server -y
          python3 -m pip install --upgrade pip
          python3 -m pip install -r requirements.txt
          ansible-galaxy collection install linode.cloud community.crypto community.mysql

      - name: build ansible environment
        run: ./run.sh build
        env:
          TOKEN: ${{ secrets.LINODE_API_TOKEN }}
          VAULT_PASS: ${{ secrets.VAULT_PASS }}
          VARS_URL: ${{ secrets.TEST_VARS_URL }}
          ROOT_PASS: ${{ secrets.ROOT_PASS }}

      - name: test ubuntu 20.04
        run: ./run.sh test:ubuntu2004

      - name: verify
        run: ./run.sh test:verify
